config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :articles do
    resources :comments, only: [:create]
  end

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]

  mount ActionCable.server => '/cable'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5, maximum: 100 }
  validates :body, presence: true, length: { minimum: 50 }
  validates :user_id, presence: true
  default_scope -> { order(created_at: :desc) }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true,
    uniqueness: { case_sensitive: false },
    length: { minimum: 3, maximum: 30 }
  default_scope -> { order(name: :asc) }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
  validates :description, presence: true, length: { maximum: 150 }
  validates :user_id, presence: true
  validates :article_id, presence: true
  default_scope -> { order(updated_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_secure_password
  validates :username, presence: true,
    uniqueness: { case_sensitive: false },
    length: { minimum: 5, maximum: 30 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?, :admin?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def admin?
    current_user.admin?
  end

  def require_user
    if !logged_in?
      flash[:danger] = 'Please log in first.'
      redirect_to root_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :find_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = 'Your article was created successfully.'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = 'Your article was successfully updated.'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
    @comment = Comment.new
  end

  def destroy
    @article.destroy
    flash[:success] = 'Your article was successfully deleted.'
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, category_ids: [])
  end

  def find_article
    @article = Article.find(params[:id])
  end

  def require_same_user
    if !admin? && current_user != @article.user
      flash[:danger] = 'You can only edit or delete your own articles.'
      redirect_to articles_path
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :find_category, only: [:edit, :update, :show]
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 10)
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = 'The category was created successfully.'
      redirect_to category_path(@category)
    else
      render 'new'
    end
  end

  def update
    if @category.update(category_params)
      flash[:success] = 'Category name was successfully updated.'
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def show
    @articles = @category.articles.paginate(page: params[:page], per_page: 10)
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def find_category
    @category = Category.find(params[:id])
  end

  def require_admin
    if !logged_in? || !admin?
      flash[:danger] = 'Only admin can create, edit or delete a category.'
      redirect_to categories_path
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :require_user

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      ActionCable.server.broadcast 'comments', render(partial: 'comments/comment', object: @comment)
    else
      redirect_to article_path(@article)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:description)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :not_logged_in, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      cookies.encrypted[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash.now[:danger] = 'Invalid username or password.'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def not_logged_in
    if logged_in?
      flash[:danger] = 'You are already logged in.'
      redirect_to articles_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: [:edit, :update, :show, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def new
    @user = User.new
    redirect_to articles_path if logged_in?
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      cookies.encrypted[:user_id] = @user.id
      flash[:success] = 'You have successfully signed up.'
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      flash[:success] = 'Your profile was successfully updated.'
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    msg = "#{@user.username}'s profile and articles have been successfully deleted."
    @user.destroy
    flash[:success] = msg
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def find_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if !logged_in? || (!admin? && current_user != @user)
      flash[:danger] = 'You can only edit your own profile.'
      redirect_to articles_path
    end
  end

  def require_admin
    if !admin?
      flash[:danger] = 'Only admin can delete a profile.'
      redirect_to users_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
    <div class="col-sm-2 control-label">
      <%= f.label :title %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :title, class: "form-control", placeholder: 'Title of the article', autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-2 control-label">
      <%= f.label :body, 'Content' %>
    </div>
    <div class="col-sm-8">
      <%= f.text_area :body, rows: 10, class: "form-control", placeholder: 'Body of the article' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-2 control-label">
      <label>Categories</label>
    </div>
    <div class="col-sm-8">
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <% cb.label(class: "checkbox-inline text-capitalize") { cb.check_box + cb.text } %>
      <% end %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-8">
      <%= f.submit @article.new_record? ? 'Create' : 'Update', class: "btn btn-default" %>
      <%= link_to 'Cancel', @article.new_record? ? articles_path : article_path(@article), class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/articles/_list.html.erb
<% articles.each do |a| %>
  <div class="panel panel-default col-sm-offset-2 col-sm-8 no-padding">
    <div class="panel-heading">
      <h3><%= link_to a.title, article_path(a) %></h3>
      <p><%= truncate(a.body, length: 250) %></p>
      <small>
        Created by <%= link_to a.user.username, user_path(a.user) %>
        , <%= time_ago_in_words(a.created_at) %> ago<br />
        Last updated <%= time_ago_in_words(a.updated_at) %> ago
      </small>
      <div class="row <%= 'space-above' if a.categories.any? %>">
        <div class="col-xs-8">
          <% if a.categories.any? %>
            Categories: <%= render a.categories %>
          <% end %>
        </div>
        <div class="col-xs-4 text-right">
          <%= link_to 'View', article_path(a) %>
          <% if logged_in? && (admin? || current_user == a.user) %>
            | <%= link_to 'Edit', edit_article_path(a) %>
            | <%= link_to 'Delete', article_path(a), method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="container">
  <div class="row">
    <h1 class="page-title col-sm-offset-2 col-sm-8">Edit Article</h1>
  </div>
  <%= render 'common/errors', obj: @article %>
  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class="container">
  <div class="row">
    <h1 class="page-title col-sm-offset-2 col-sm-8">Articles</h1>
  </div>
  <%= render 'list', articles: @articles %>
  <div align="center">
    <%= will_paginate @articles %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="page-title col-sm-offset-2 col-sm-8">Create Article</h1>
  </div>
  <%= render 'common/errors', obj: @article %>
  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="container">
  <h1 class="page-title col-sm-offset-2 col-sm-8">
    <div class="row">
        <%= @article.title %>
    </div>
  </h1>
  <div class="col-sm-offset-2 col-sm-8 no-padding">
    <h5 class="article-details">
      Created by <%= link_to @article.user.username, user_path(@article.user) %>
      , <%= time_ago_in_words(@article.created_at) %> ago<br />
      Last updated <%= time_ago_in_words(@article.updated_at) %> ago
    </h5>
    <div class="row <%= 'space-below' if @article.categories.any? %>">
      <div class="col-xs-8 h5">
        <% if @article.categories.any? %>
          Categories: <%= render @article.categories %>
        <% end %>
      </div>
      <div class="col-xs-4 text-right h5">
        <% if logged_in? && (admin? || current_user == @article.user) %>
          <%= link_to 'Edit', edit_article_path(@article) %>
          | <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    </div>
    <p class="space-above space-below"><%= @article.body %></p>
    <% if logged_in? %>
      <%= form_for([@article, @comment], :html => {class: "space-below space-above", role: "form"}, remote: true) do |f| %>
        <div class="form-group">
          <%= f.label :description, 'Comment', class: "sr-only" %>
          <%= f.text_area :description, rows: 3, class: "form-control", placeholder: 'Add a comment.', id: "comment-form" %>
        </div>
        <%= f.submit 'Add', class: "btn btn-default" %>
      <% end %>
    <% end %>
  </div>
  <div id='notes'>
    <%= render @article.comments %>
  </div>
</div>

app/views/categories/_category.html.erb
<span class="label label-primary category-chip">
  <%= link_to category.name, category_path(category), class: "chip text-capitalize" %>
</span>

app/views/categories/_form.html.erb
<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
    <div class="col-sm-2 control-label">
      <%= f.label :name %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :name, class: "form-control", placeholder: 'Enter category name', autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-8">
      <%= f.submit @category.new_record? ? 'Create' : 'Update', class: "btn btn-default" %>
      <%= link_to 'Cancel', @category.new_record? ? categories_path : category_path(@category), class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
  <div class="row">
    <h1 class="page-title col-sm-offset-2 col-sm-8">Edit Category</h1>
  </div>
  <%= render 'common/errors', obj: @category %>
  <%= render 'form' %>
</div>

app/views/categories/index.html.erb
<div class="container">
  <div class="row">
    <h1 class="page-title col-sm-offset-2 col-sm-8">Categories</h1>
  </div>
  <% @categories.each do |c| %>
    <div class="panel panel-default col-sm-offset-2 col-sm-8 no-padding">
      <div class="panel-heading">
        <h3 class="text-capitalize"><%= link_to c.name, category_path(c) %></h3>
        <div class="row">
          <div class="col-xs-6">
            <p><%= pluralize(c.articles.count, 'article') %></p>
          </div>
          <div class="col-xs-6 text-right">
            <%= link_to 'View', category_path(c) %>
            <% if logged_in? && admin? %>
              | <%= link_to 'Edit', edit_category_path(c) %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div align="center">
    <%= will_paginate @categories %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="page-title col-sm-offset-2 col-sm-8">Create Category</h1>
  </div>
  <%= render 'common/errors', obj: @category %>
  <%= render 'form' %>
</div>

app/views/categories/show.html.erb
<div class="container">
  <h1 class="page-title col-sm-offset-2 text-capitalize col-sm-8">
    <div class="row">
      Category: <%= @category.name %>
    </div>
  </h1>
  <div class="col-sm-offset-2 col-sm-8 no-padding">
    <div class="row space-below">
      <h4 class="col-xs-6">
        <%= pluralize(@category.articles.count, 'article') %>
      </h4>
      <div class="col-xs-6 text-right h4">
        <% if logged_in? && admin? %>
          <%= link_to 'Edit', edit_category_path(@category) %>
        <% end %>
      </div>
    </div>
  </div>
  <%= render 'articles/list', articles: @articles %>
  <div align="center">
    <%= will_paginate @articles %>
  </div>
</div>

app/views/comments/_comment.html.erb
<div class="panel panel-info col-sm-offset-2 col-sm-8 no-padding">
  <div class="panel-heading">
    <p><%= comment.description %></p>
    <small>
      By <%= link_to comment.user.username, user_path(comment.user) %>
      , <%= time_ago_in_words(comment.created_at) %> ago
    </small>
  </div>
</div>

app/views/common/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h4><%= pluralize(obj.errors.count, 'Error') %>:</h4>
          <ul>
            <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'KY BLOG', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Articles', articles_path %></li>
        <li><%= link_to 'Users', users_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Categories<span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'All Categories', categories_path %></li>
            <% if Category.any? %>
              <li role="separator" class="divider"></li>
            <% end %>
            <% Category.all.each do |c| %>
              <li class="text-capitalize"><%= link_to c.name, category_path(c) %></li>
            <% end %>
            <% if logged_in? && admin? %>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Create New Category', new_category_path %></li>
            <% end %>
          </ul>
        </li>
        <% if logged_in? %>
          <li><%= link_to 'Create New Article', new_article_path, class: "new-article" %></li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              Your<%= ' Admin' if admin? %> Profile<span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'View Your Profile', user_path(current_user) %></li>
              <li><%= link_to 'Edit Your Profile', edit_user_path(current_user) %></li>
            </ul>
          </li>
          <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign Up', signup_path %></li>
          <li><%= link_to 'Log In', login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_notices.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |type, msg| %>
      <div class="alert alert-<%= type %> alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/notices' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>KY BLOG</h1>
    <p>Write articles on topics you are passionate about and share with other users!</p>
    <p>
      <%= link_to 'Sign Up', signup_path, class: "btn btn-primary btn-lg", role: "button" %>
    </p>
  </div>
</div>

<div class="container">
  <div class="row">
    <% Article.last(3).reverse.each do |a| %>
      <div class="col-sm-4">
        <h2><%= a.title %></h2>
        <p><%= truncate(a.body, length: 150) %></p>
        <p>
          <%= link_to 'Read More', article_path(a), class: "btn btn-default", role: "button" %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
    <div class="col-sm-2 control-label">
      <%= f.label :username %>
    </div>
    <div class="col-sm-8">
      <%= f.text_field :username, class: "form-control", placeholder: 'Enter username', autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-2 control-label">
      <%= f.label :password %>
    </div>
    <div class="col-sm-8">
      <%= f.password_field :password, class: "form-control", placeholder: 'Enter password' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-8">
      <%= f.submit @user.new_record? ? 'Sign up' : 'Update', class: "btn btn-default" %>
      <% if !@user.new_record? %>
        <%= link_to 'Cancel', user_path(@user), class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <h1 class="page-title col-sm-offset-2 col-sm-8">Edit Profile</h1>
  </div>
  <%= render 'common/errors', obj: @user %>
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h1 class="page-title col-sm-offset-2 col-sm-8">Users</h1>
  </div>
  <% @users.each do |u| %>
    <div class="panel panel-default col-sm-offset-2 col-sm-8 no-padding">
      <div class="panel-heading">
        <h3>
          <%= link_to u.username, user_path(u) %>
          <% if u.admin? %>
            <span class="label label-info">Admin</span>
          <% end %>
        </h3>
        <div class="row">
          <div class="col-xs-6">
            <p><%= pluralize(u.articles.count, 'article') %></p>
          </div>
          <div class="col-xs-6 text-right">
            <%= link_to 'View', user_path(u) %>
            <% if logged_in? && current_user == u %>
              | <%= link_to 'Edit', edit_user_path(u) %>
            <% end %>
            <% if logged_in? && admin? %>
              | <%= link_to 'Delete', user_path(u), method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div align="center">
    <%= will_paginate @users %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="page-title col-sm-offset-2 col-sm-8">Sign Up</h1>
  </div>
  <%= render 'common/errors', obj: @user %>
  <%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1 class="page-title col-sm-offset-2 col-sm-8">
    <div class="row">
      <%= @user.username %>
      <% if @user.admin? %>
        <span class="label label-info">Admin</span>
      <% end %>
    </div>
  </h1>
  <div class="col-sm-offset-2 col-sm-8 no-padding">
    <div class="row space-below">
      <h4 class="col-xs-6">
        <%= pluralize(@user.articles.count, 'article') %>
      </h4>
      <div class="col-xs-6 text-right h4">
        <% if logged_in? && current_user == @user %>
          <%= link_to 'Edit', edit_user_path(@user) %>
        <% end %>
        <%= '|' if logged_in? && current_user == @user && admin? %>
        <% if logged_in? && admin? %>
          <%= link_to 'Delete', user_path(@user), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    </div>
  </div>
  <%= render 'articles/list', articles: @articles %>
  <div align="center">
    <%= will_paginate @articles %>
  </div>
</div>